### ISSUE TITLE
Apple Silicon M1

### ISSUE THREAD

**Issue by holtwick** [SwiftyTesseract/libtesseract#4]
Hi, are you planning to support the M1 chip? 

I looked into the code and it seems to be well prepared for the task in general. I hope that adding some `lipo` call will fix the issue: https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary#3618377

Since I'm not great in doing low level Makefile writing, I wondered if you'd take a look ;)

**Comment by Steven0351** [comment]
Ideally I wouldn’t need to use Lipo and will hopefully just be able to utilize xcframework and have an arm64 specific variant for the m1 and have that bundled with the other platform specific frameworks. I can definitely look into it. Do you have an m1 machine that you would be willing to do some validation with before I cut a release and publish it for general consumption?

**Comment by holtwick** [comment]
That sounds great, thanks a lot. Yes I own a MacBook Air M1 and can validate and help with builds.

**Comment by holtwick** [comment]
Well I already experimented a bit and it seems to work well locally. But it throws a "Found an unexpected Mach-O header code: 0x72613c21" when validating with the AppStore. Although this could be a local issue somehow. These are my changes:

https://github.com/SwiftyTesseract/libtesseract/compare/develop...holtwick:feature/m1

**Comment by Steven0351** [comment]
I looked at your changes and you may be getting that issue because you are lipoing the m1 and x86 binaries together. Try building them as separate frameworks and combine them into an xcframework like the rest of the frameworks and that may fix that issue.

**Comment by holtwick** [comment]
Thanks for your help. The reason seemed to be that somehow the framework was embedded into my app instead of linked against. Still figuring it all out ;)

**Comment by Steven0351** [comment]
You may want to take a look at https://github.com/SwiftyTesseract/libtesseract/issues/3 for the embedding issue. Someone has a fix there for that

**Comment by holtwick** [comment]
Yes, this seems to be the reason. The `lipo` is not the cause. Probably a SwiftPM issue. The resulting `libtesseract.xcframework` seems do be fine though. Not using it inside a Swift Package did not throw any error anymore, when verifying with Apple.

**Comment by Steven0351** [comment]
Keep open

**Comment by Steven0351** [comment]
M1 is now fully supported for iOS simulator and macOS as of version 0.2.0
